# This workflow will do a clean installation of node dependencies, build the source code and check for issues.
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Krafton SoC Web PR CI

on:
  pull_request:
    branches: ["main", "dev"]

jobs:
  lint-build-typecheck:
    name: Lint, Build, and Type Check
    runs-on: ubuntu-latest # Use ubuntu-latest for broader compatibility

    strategy:
      matrix:
        node-version: ["20.x"] # Use Node.js 20 LTS

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm" # Enable caching for pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Check types
        run: pnpm typecheck

      - name: Check linting
        run: pnpm lint

      - name: Check build passing
        run: pnpm build
